# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.mongodb-binaries
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn run lint:fix
      - run: yarn test
      - run: yarn run coverage

  staging:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - nowcli-11.4.1

      - run: yarn global add now@11.4.1

      - save_cache:
          paths:
            - .config/yarn/global/node_modules
          key: nowcli-11.4.1

      - run: now -t ${NOW_TOKEN} remove ireversi-server -y
      - run: now -t ${NOW_TOKEN} --public -e MONGO_URI=@ireversi-mongo-uri -n ireversi-server
      - run: now -t ${NOW_TOKEN} alias
      - run: now -t ${NOW_TOKEN} scale ireversi-server.now.sh 1

workflows:
  version: 2
  test_and_staging:
    jobs:
      - test
      - staging:
          requires:
            - test
          filters:
            branches:
              only: develop
